// <auto-generated />
using System;
using API.Repo.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(Repository))]
    partial class RepositoryModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("API.Models.Adress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adress", "ApiBase");
                });

            modelBuilder.Entity("API.Models.Aducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NameCourse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aducation", "ApiBase");
                });

            modelBuilder.Entity("API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AdressId")
                        .HasColumnType("int");

                    b.Property<int?>("AducationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("NamePerson");

                    b.Property<string>("Surname")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("SurnamePerson");

                    b.HasKey("Id");

                    b.HasIndex("AdressId");

                    b.HasIndex("AducationId");

                    b.ToTable("Persons", "ApiBase");
                });

            modelBuilder.Entity("API.Models.Person", b =>
                {
                    b.HasOne("API.Models.Adress", "AdressPerson")
                        .WithMany()
                        .HasForeignKey("AdressId");

                    b.HasOne("API.Models.Aducation", "Course")
                        .WithMany("Persons")
                        .HasForeignKey("AducationId");

                    b.Navigation("AdressPerson");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("API.Models.Aducation", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
